### ISSUE TITLE
Create helper file for e2e tests

### ISSUE THREAD

**Issue by adamcee** [gri-is/portal#284]
Create `test/helper.js` (or similarly named file). Add various helper functions there to reduce code duplication when writing e2e tests. 

Potentially, also go through existing e2e tests and refactor to be more DRY where possible, finding code which is duplicated, creating a helper function for it, adding it to the helper file, and then replacing said code. 

Potential Resource: The John Papas "modular" sample angular app, which can be found in his repo here: https://github.com/johnpapa/ng-demos

**Comment by jfranco-gri** [comment]
I think we've accomplished this through the use of page objects.
