### ISSUE TITLE
individual facet chips for new keyword searches

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#349]

**Comment by adamcee** [comment]
Bug - on the search results page if you type "painting", hit enter, and type "painting again, there are no keyword facets in the search box **and** the URL has the same `q` term twice.

**Comment by joshuago78** [comment]
Excellent catch

**Comment by jfranco-gri** [comment]
Bug should be fixed now

**Comment by adamcee** [comment]
Oh! Sorry for the PR comments here -meant to put on the PR not the issue. My bad :/
