### ISSUE TITLE
pageSize=10 edge case pagination bug

### ISSUE THREAD

**Issue by adamcee** [gri-is/portal#359]
@joshuago78 Found this while working on a pagination enhancement.  I'm labelling it "high severity" b/c its a behavior bug, but It's definitely an edge case.

Changing from `pageSize=10` to `pageSize=25` in certain cases will result in some undisplayed records if the user paginates backwards.

**To Reproduce**
1. Run an empty search.
2. Change page size to 10.
3. Paginate to page 5. Note that you are viewing results 41-50.
4. Change page size to 25. Note that the page number is changed to 2, and you are still viewing results 41-50.
5. Paginate back to page 1. Note that you are viewing results 1-25. **Results 25-41 have been lost.**

@kristenGRI What is the desired behavior in this case? Jenny and I brainstormed some approaches but it depends on how we want pagination to behave for the user, we could not think of a perfect solution in this case.

**Comment by jfranco-gri** [comment]
Now that we have pagination reset to 1 when pageSize changes, this should no longer be an issue.
