### ISSUE TITLE
IE styling compatibility issues (Search Results Page)

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#383]
Facets not wrapping properly...

![image003](https://cloud.githubusercontent.com/assets/349633/14114583/514bc6ce-f58c-11e5-883d-bc7371c1f73c.jpg)

**Comment by kristenGRI** [comment]
Noting I am going to use this ticket to resolve IE compatibility issues on the Search results page. These issues are:

- [ ] Facets not wrapping (IE 10/11)

- [ ] Date range spilling out of sidebar on narrow display (IE 10/11) and wraps in IE 9

- [ ] Add/Remove text floats to the right of the bookmark, not under it (IE 9/10/11)

- [ ] Lots of space between facet ships in the search bar (IE 10/11)

- [ ] Search button wraps in narrow display (IE 9)

- [ ] Pagination still wraps in narrow display when Sort by: Newly Added first and Show 25 are checked and all page numbers are 4 digits. (IE 9/10/11)

Most are small CSS adjustments. Should be pretty straightforward.
