### ISSUE TITLE
inconsistent ASCII folding

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#384]
Another bug found by Annie...

> I noticed something strange, which occurs in both the old and new Portal. When you search the author Heinrich Wolfflin in both the old/new instances, it doesn’t return any results from the GRI.  When you search ‘Wölfflin, Heinrich’ (the correct way to spell his name), it still doesn’t return any GRI titles in both instances.
But then I looked up one of his titles that I know we have in there—you can do any of the below—and if you enlarge the screenshot, you’ll see his name appears with the umlaut shifted a bit past the ‘o’. So then I copied this from the old Portal and tried it in the new Portal and it yielded the GRI results. (But not Heidelberg ones which come up if you do his name with or without the umlaut). Anyway wanted to bring to your attention. Given Wolfflin’s status, I figure it’s one we should get right!

**Comment by adamcee** [comment]
@joshuago78 Just tested this manually and it seems to work. I searched on portal beta for "Heinrich Wolfflin" and got results.

http://portalbeta.getty.edu/search?q=heinrich%20wolfflin&from=0&size=25&sort=relevance

Should we close this?

**Comment by joshuago78** [comment]
No, her bug report says that GRI titles are not showing up. If you look at your search, you will notice that none of the hits belong to the GRI.

If you look at these results you'll see that we do indeed have titles by him in the Portal: http://portalbeta.getty.edu/search?q=die%20klassische%20kunst%20eine%20einfu%CC%88hrung%20in%20die%20italienische&from=0&size=25&sort=relevance

So, for some reason, the GRI records for this author (and who knows how many others) are not getting the proper ASCII folding

**Comment by joshuago78** [comment]
An initial clue is that the GRI records have his name in the creator field, whereas the other institutions have him in the contributor field. Are the mappings slightly different? I don't think so, but we should double check.

Another clue is that the GRI records have his life span in the same field. Could the numerals be throwing off the folding? I don't know.

**Comment by adamcee** [comment]
Ah - I missed that it was GRI records specifically which were not showing up. Thanks. 

Interestingly, an advanced search for creator = "Heinrich Wolfflin" turns up one non-Getty result. Not sure what that means. It also has the name / life span in the creator field. 

http://portalbeta.getty.edu/search?from=0&size=25&sort=relevance&adv_creator=heinrich%20wolfflin

**Comment by adamcee** [comment]
Also, if you open the "Creator / Contributor " facet modal and search for Heinrich, you will see *two* "Heinrich Wolfflin" (with diacritics) facet options. One will have all the records where Heinrich is the "creator", the others where he is the "contributor".

**Comment by joshuago78** [comment]
This org has metadata similar to ours http://portalbeta.getty.edu/books/gugg_1907753

It's in the creator field and has the life span. So those earlier clues now seem dead ends.

This makes me wonder if there is just something particular to GRI data that is causing this

**Comment by joshuago78** [comment]
OK, @adamcee last comment shows the heart of the problem. How are there two facets with the exact same value?

**Comment by adamcee** [comment]
I was wondering if maybe at some point, since our "facet" we expose to the user is a combination of Elasticsearch aggregations, the "creator" field aggregation for Wolfflin and "contributor" field aggregation for Wolfflin both get added to the "facet" which is exposed to the user. Haven't done any investigation - just an idea.

**Comment by joshuago78** [comment]
Yes, I bet you are correct.

However, that does not explain why our material does not show up when doing a keyword search

**Comment by adamcee** [comment]
I agree. It may be that the two issue are unrelated.
