### ISSUE TITLE
Fix e2e Test -- "Search Results should update bookmarks for records saved in other tabs"

### ISSUE THREAD

**Issue by adamcee** [gri-is/portal#411]
E2E test failure on develop branch in `search-results.e2e.spec.js`. As of 4/19/16 ... 

The actual feature *"Search Results should update bookmarks for records saved in other tabs"* works when I tested locally on develop.

Details:
````
Failures:
1) Search Results should update bookmarks for records saved in other tabs
  Message:
    Failed: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By.cssSelector(".item-details .bookmark")
  Stack:
    Error: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By.cssSelector(".item-details .bookmark")
        at process._tickCallback (node.js:402:9)
    Error
        at Object.create.clickBookmark.value (/Users/acahan/projects/portal/test/page_objects/book-detail.page.js:9:66)
        at /Users/acahan/projects/portal/test/e2e/search-results.e2e.spec.js:113:24
        at process._tickCallback (node.js:402:9)
    From: Task: Run it("should update bookmarks for records saved in other tabs") in control flow
````

@joshuago78 FYI I was trying to decide if it made sense to create a label specific to tests for this Issue but couldn't think of an appropriate way to do it ....

**Comment by jfranco-gri** [comment]
This is because the book-detail page used to have a class called 'item-details' but it looks like that was removed. There's now an id called "item-details" but the test wasn't updated to reflect that.
