### ISSUE TITLE
"Total Titles" on home page not working

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#414]
to reproduce:
1. perform a search
2. select a few facets
3. click on the home page link
4. See the total titles is now limited by your search facets

**Comment by alyxrossetti** [comment]
@joshuago78 "Total Titles" appears to be working at the moment. We can discuss at today's meeting.

**Comment by joshuago78** [comment]
This bug has returned. Subsequent commits must have reintroduced it to the code. That means the e2e test is not properly testing it. Instead of doing `var homePage2 = new HomePage();` maybe you should click on the "Home" button of the current `homePage` object.
