### ISSUE TITLE
generate historical ingest dates

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#432]
- [x] change funnel code to add ingest dates
- [x] process test files
- [x] process full set
- [x] update temporary database (in prep for ingest system)
- [x] create upload order sequence

**Comment by alyxrossetti** [comment]
@joshuago78 For the upload order sequence - do you want a single sequence a separate sequence for each institution.  The order really only matters within each institution...

**Comment by joshuago78** [comment]
No preference

**Comment by alyxrossetti** [comment]
@joshuago78 All tasks for this issue complete
