### ISSUE TITLE
create IE VMware container

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#435]

**Comment by lolliffe** [comment]
Original install prompted for 173 updates, running that dropped to 49, then 12, then 3.  Of those 3, 2 kept erring out, so I tried a manual refresh for updates.  That brought back 426 updates, which are currently downloading. (11am 2016-05-05)

I've also installed the latest Chrome and Firefox browsers.  I'm leaving everything as freshly installed, but functional, as possible, for Dev's to customize as they like.

I'm currently running an older version of VMWare (7.1, the current is 8.x), so the containers will need to be updated by the app itself the first time that it's run.

Once I have the image, I'll put it in a dated folder, so Dev's will know when it was last updated, zip the directory, and put it someplace on an accessible server for downloading.  I intend to document everything, but it's pretty straightforward.
