### ISSUE TITLE
add link to old Portal

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#447]

**Comment by kristenGRI** [comment]
Here are two simple options I came up with. I imagine we want to promote the new version more than the old one so I'm assuming something more discreet would be ideal. In v1. I've added the link next to the other footer links (possibly too discreet?). V2 has the link with some (temp) copy just about the footer.
![old-portal-link_v1](https://cloud.githubusercontent.com/assets/15019503/15379931/78957dc6-1d26-11e6-838b-233c467572e2.png)
![old-portal-link_v2](https://cloud.githubusercontent.com/assets/15019503/15379932/7896601a-1d26-11e6-9ae1-dd6c8ec15225.png)

Let me know what you think.

**Comment by joshuago78** [comment]
Let's go with your second option, but instead of "old portal", use "previous version of the Portal"
