### ISSUE TITLE
relative urls

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#448]
Remove full URLs from application code to make DNS switch easier

**Comment by adamcee** [comment]
@joshuago78 I think all the url routes in the angular code are relative to the base URL, so the only thing which needs to be changed is the host name and the URL root. 

I have moved those values out of `/src/client/app/core/constants.js` and into `/src/client/env.js` and am following the approach suggested below for setting up dynamic client config per environment. 
http://www.jvandemo.com/how-to-configure-your-angularjs-application-using-environment-variables/

This currently passes E2E tests and works when tested manually, but unit tests need to be adjusted.

Ideally we'll use a script or something generate an `env.js` file for each environment based on system environment vars. There is a node module someone has written which may work for this, or we can write a shell script to build the file.
