### ISSUE TITLE
hook up front-end code to api

### ISSUE THREAD

**Issue by jfranco-gri** [gri-is/portal#451]

**Comment by jfranco-gri** [comment]
I tried to get our angular app to talk to the api but it's not working due to them not running on the same host (the app uses local.portal.dev and I haven't been able to get the django app to run on that). So I think #405 needs to be settled before I can start work on this.

**Comment by jfranco-gri** [comment]
Got django-cors-header working so now the angular app can talk to the django api 🎉 
The book detail and contributors pages are now using the api to get the data 🎉 
I also fixed and cleaned up the relevant unit tests and E2E tests so they are now passing.

**Comment by adamcee** [comment]
NICE 😸 

FYI you may want to keep an eye on my PR for frontend dependencies as it gets rid of the `config` constant, if you have added config settings for the API. 
https://github.com/gri-is/portal/pull/476
