### ISSUE TITLE
mock up 100K volumes announcement

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#455]

**Comment by kristenGRI** [comment]
Just for clarification, I am assuming this announcement will be on the homepage of the portal? Or is this a promo image that will exist on the page about the Research Portal?

**Comment by joshuago78** [comment]
Yes, this will be on the homepage of the app, not the website page.

**Comment by kristenGRI** [comment]
Here are a few versions. Obviously the copy is temp. The image for v4 is also temp, just something I grabbed from the GRI page carousel. I can also create or find different icons if you like the how the icon looks but icon itself could be better.

Noting that the more I think about it, the more I feel like we should keep "See All Titles" in  total titles opposed to a button below the search. I think having the space below search area is nice in case we want to announce or promote things in the future.
![rp_100k_announcement_v1](https://cloud.githubusercontent.com/assets/15019503/15412489/e257cabe-1ddc-11e6-9fc0-fa3e0ede9596.jpg)
![rp_100k_announcement_v2](https://cloud.githubusercontent.com/assets/15019503/15412490/e259f2d0-1ddc-11e6-9565-2ba2d2a86632.jpg)
![rp_100k_announcement_v3](https://cloud.githubusercontent.com/assets/15019503/15412491/e25e9998-1ddc-11e6-91bd-0a2cb41b1ae5.jpg)
![rp_100k_announcement_v4](https://cloud.githubusercontent.com/assets/15019503/15412492/e25fe190-1ddc-11e6-92d5-85c373a5ff1f.jpg)

**Comment by joshuago78** [comment]
These don't take into account that we are putting the "see all records" button back in

**Comment by kristenGRI** [comment]
Adding new versions with the button added back in.
![rp_100k_announcement_v1 1](https://cloud.githubusercontent.com/assets/15019503/15441587/98cc3006-1e90-11e6-9abe-18348967293f.jpg)
![rp_100k_announcement_v2 1](https://cloud.githubusercontent.com/assets/15019503/15441589/98cfd206-1e90-11e6-8260-b8c52e71ce10.jpg)
![rp_100k_announcement_v3 1](https://cloud.githubusercontent.com/assets/15019503/15441588/98cc573e-1e90-11e6-97fc-0d1afb494f90.jpg)
![rp_100k_announcement_v4 1](https://cloud.githubusercontent.com/assets/15019503/15441590/98d09ff6-1e90-11e6-8254-4fdb33d1def9.jpg)

**Comment by joshuago78** [comment]
I don't like the one with the photo in it.

More importantly, this announcement is for reaching 100K **volumes**, not titles.

**Comment by kristenGRI** [comment]
Updated the other 3 with the correct text. Let me know if you want any additional versions or tweaks the existing designs.
![rp_100k_announcement_v1 2](https://cloud.githubusercontent.com/assets/15019503/15479787/d3b6c71a-20d6-11e6-9472-0457f79f7ce8.jpg)
![rp_100k_announcement_v2 2](https://cloud.githubusercontent.com/assets/15019503/15479788/d3b89856-20d6-11e6-8654-46a21276a36a.jpg)
![rp_100k_announcement_v3 2](https://cloud.githubusercontent.com/assets/15019503/15479789/d3bc9e2e-20d6-11e6-8967-f54bd67dc602.jpg)

**Comment by kristenGRI** [comment]
This is the approved design. Let me know when it needs to be added to the site.
![rp_100k_announcement_v6_alt](https://cloud.githubusercontent.com/assets/15019503/15755433/a37a3c7a-28b1-11e6-8726-a67712eeeb13.jpg)

**Comment by joshuago78** [comment]
Go ahead and make a pull request for it. We'll merge it sometime next week.
