### ISSUE TITLE
pagination broken on full data set

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#469]
- Use the alpha (http://grpdev.getty.edu) or the beta (http://portalbeta.getty.edu).
- Perform an empty search
- Click on the last page button: `>>`
- Notice that the results do not change, and neither does the `from` parameter in the URL

This functionality works correctly when I run it locally on the test set of records.

**Comment by jfranco-gri** [comment]
Pagination works up until 10000 records. This works:
`http://portalbeta.getty.edu/search?q=art&from=9999&size=1&sort=relevance`

but this does not:
`http://portalbeta.getty.edu/search?q=art&from=10000&size=1&sort=relevance`

note that in the first query, I am asking for record 10000 and in the second, I am asking for record 10001.

**Comment by joshuago78** [comment]
Yes, this has already been resolved (see the Slack dialogue). Just waiting for Github to recover so I can submit the Pull Request
