### ISSUE TITLE
Mobile devices should not display keyboard when user selects facet option

### ISSUE THREAD

**Issue by adamcee** [gri-is/portal#479]
Currently when the user selects a facet option the app focuses on/places the cursor in the search box. This is desirable for laptops and desktops, but is not desirable for mobile/tablet devices because the keyboard then pops up on the device which interrupts the flow for the user.

On a mobile/tablet, when the user selects a facet option the app should not focus on the search box and the mobile device keyboard should not be displayed.

**Comment by jfranco-gri** [comment]
This used to happen on my phone, (iPhone 4) but does not anymore. Is this still an issue on other phones?

**Comment by joshuago78** [comment]
It's happening on my phone (Samsung Galaxy Note 5)

**Comment by susanley** [comment]
Happens on Galaxy S6 as well.
