### ISSUE TITLE
Use ng-cloak to hide html template during page load

### ISSUE THREAD

**Issue by adamcee** [gri-is/portal#480]
On slow mobile devices - specifically iPhone 3G using Safari - the html template is visible during page load when the user paginates on the search results page. It would be interesting to test if this also occurred on older desktops or slow internet connections. 

Use ng-cloak to hide html template during page load

https://docs.angularjs.org/api/ng/directive/ngCloak

**Comment by susanley** [comment]
@joshuago78 Just tested again with @adamcee. This issue has been resolved.

**Comment by joshuago78** [comment]
I noticed that the Angular code briefly displayed during a demo last week. Please revisit this issue.
