### ISSUE TITLE
Facet-modal search box does not handle diacritics

### ISSUE THREAD

**Issue by adamcee** [gri-is/portal#487]
*To Reproduce*

1. Go to portalbeta.getty.edu or grpdev.getty.edu
2. Open the facet modal for "Creator / Contributor"
3. Search for "wolfflin" - there should be no results.
4. Now search for "heinrich" - there should be several results, including at least one facet option for "Heinrich Wolflinn" where "Wolflinn has diacritics

--------------
*Resources*

https://github.com/Kepro/angular-remove-diacritics
http://alistapart.com/article/accent-folding-for-auto-complete -- good article, also has code
https://github.com/aristus/accent-folding (from above article - contains both `.js` and `.py` accent folding code)

http://stackoverflow.com/questions/990904/remove-accents-diacritics-in-a-string-in-javascript

**Comment by adamcee** [comment]
Do we want to think about #497 before tackling this?

**Comment by joshuago78** [comment]
- [ ] research Unicode standardization software
