### ISSUE TITLE
"See New Records" link does nothing

### ISSUE THREAD

**Issue by adamcee** [gri-is/portal#488]
@joshuago78  FYI. 
Currently the "See New Records" link does not perform any action or link to any page. 

May be related to #222 ?

**Comment by joshuago78** [comment]
No this is not related to 222. But this is a serious bug

**Comment by adamcee** [comment]
I was making a list of what links we want to allow for crawlers, etc, and noticed it ....

**Comment by adamcee** [comment]
@joshuago78 @alyxrossetti What criteria do we want to use to filter results for this page? `ingest_date`? Something else?
Should this link take the user to the search results page?
What are additional specs for this Issue?

**Comment by alyxrossetti** [comment]
@adamcee yes we would use `_ingest_date` - but I don't know how we want to define "new".  @joshuago78 What are your thoughts?  The last 30 days?  The current quarter?  And yes I would think the link would go the search results page

**Comment by adamcee** [comment]
@joshuago78 Alyx and I talked offline and I am going to whip up a PR which directs "See New Records" to: http://local.portal.dev:8000/search?from=0&size=25&sort=date_added

That seems to make sense and, worst case, can serve in the interim if its not a final solution.

**Comment by joshuago78** [comment]
yes, that was the intended behavior

**Comment by adamcee** [comment]
Awesome :). There is a PR for it w/tests.
