### ISSUE TITLE
Write python script to create sitemap files for book detail pages

### ISSUE THREAD

**Issue by adamcee** [gri-is/portal#490]
@joshuago78 the implementation spec is based on conversations w/ @alyxrossetti and research. It should be pretty simple, as basically it's just creating `.txt` files. 

The bulk of our sitemap is the item detail page URL's, and I believe the rest of it can be done by hand for now as it is mainly help/FAQ pages.

Down the line, the thing which will effect SEO the most I think is the `lastmod` property. We can use this to indicate to crawlers when we have new/changed records.

We should also set the `priority` of record URL's to be higher than other pages - 0.8 (scale of 0 to 1) is a value I have seen in many examples. And maybe set, say, the 'Feedback' page to have priority `0.3`.

The `changefreq` prop does not seem as critical for us right now. 

------------

Write a python script to generate sitemap files with URL's for individual book detail pages. We will then run this script every time we have new or changed records to index in Elasticsearch. Eventually it can be connected to a database and/or our ingest pipeline. For now it can be simple. 

http://www.sitemaps.org/protocol.html
- Sitemaps can include links to other sitemap files. We should have a 'master' sitemap index `.xml` file which includes links to sitemap files for the individual record URL's. 
  - Each file must have no more than 50,000 URL's and be less than 10MB
  - Each file can be in `.xml` or `.txt` format. I recommend, for now, `.txt` format, which is simply a list of URL's - one per line. 
- The python script can either get `_grp_id` and `ingest_date` values from the database @alyxrossetti is working on, or from reading the batch record files which are prepared for indexing into Elasticsearch.
  - The script should never allow a `lastmod` date (say, from a bad `ingest_date` val)  <  current date (date script is ran).
- The script should output `.txt` files following the format specified above to the desired directory.
- The script should update the sitemap index file(master file) to include links to each 'child' sitemap file. See link above for specs on this.
  - The script should set `lastmod` and `priority` properties in the site index file associated with each 'child' file (**note:** this is nice but not critical for launch -- we can always set `lastmod` manually for going live and update later). 
- The python script should be written so that it will be easy to modify to receive data via a file or from a database, and so that it can be called by a larger application in the future.

**Comment by joshuago78** [comment]
See this as a point of reference: https://github.com/gwu-libraries/launchpad/blob/master/lp/ui/management/commands/make_sitemap.py
