### ISSUE TITLE
Opening FAQ accordion causes visual 'glitch' of page - Chrome Only

### ISSUE THREAD

**Issue by adamcee** [gri-is/portal#500]
Noticed this while working on a different issue.

@kristenGRI You should notice a slight 'shifting' of the entire page to the right. It looks like this may be being caused by Chrome's scrollbar appearing. So I'm not sure if it's an issue with our code or simply how Chrome works. 

This only occurred for me in Chrome Version 50.0.2661. Tested Safari Version 9.0.3 and Firefox 46.0.1 and did not see error.

**To Reproduce**
1. Using Chrome, open the FAQ page on the Portal Beta site (or any other Portal site).
2. Click on one of the FAQ accordions to open it.

**Comment by kristenGRI** [comment]
@adamcee this actually happens in Safari and FF too and it is due to the scrollbar appearing. Since this is how the browser handles adding in the scrollbar, there is not much we can do about it.
