### ISSUE TITLE
Angular app breaks on bad route if Elasticsearch is down

### ISSUE THREAD

**Issue by adamcee** [gri-is/portal#511]
**To Reproduce**
0. Stop Elasticsearch, but keep the API up.
1. Enter a bad route into the address bar, like `local.portal.dev/badroute`
2. The page should now perpetually attempt to reload. This is because the router has no error handling for a bad route.

**Desired Behavior**
The app should gracefully display an error message to the user informing them this page does not exist, or default to the homepage. 

There is a `$stateChangeError` event so this should be a straightforward fix.

**Resources/Possible Implementations for Fixes**
http://www.mentalspike.com/2014/09/05/bad-routes-in-angular-ui-router/
http://stackoverflow.com/questions/22936865/handling-error-in-ui-routers-resolve-function-aka-statechangeerror-passing-d

**Comment by joshuago78** [comment]
When I try this on the beta site, it reroutes me to the home page: portalbeta.getty.edu/dhqwygdqu

**Comment by adamcee** [comment]
It only happens if Elasticsearch is down. So it's not nearly as critical as I originally thought. I was stress-testing the app yesterday and had killed Elasticsearch to see what failed and how it failed.

**Comment by joshuago78** [comment]
If elasticsearch is down the app will not work and we have bigger problems than routing.

**Comment by adamcee** [comment]
True. But Apache would still serve up the angular app, so even if Elasticsearch or the API is down the app isn't dead entirely. I was thinking of graceful failures in that case. Also if Elasticsearch chokes on a query for some reason, if it isn't handled correctly in the API we could see these kinds of issues in the angular app.
