### ISSUE TITLE
IE 9/10/11: Export to Json doesn't work

### ISSUE THREAD

**Issue by kristenGRI** [gri-is/portal#512]
1. Go to http://grpdev.getty.edu:8080/ in any version of IE
2. Go to the search results page
3. Click any book title to go to the detail page (ex: http://grpdev.getty.edu:8080/books/bnf_bpt6k6313333j)
4. Click the export drop-down
5. Click DC-JSON

Bug: Nothing happens. In the console in IE 10 I see this error:
TypeError: Unable to set property 'download url' of undefined or null reference
(screenshot attached with rest of error)
![screen shot 2016-06-07 at 4 31 43 pm](https://cloud.githubusercontent.com/assets/15019503/15878453/e459f538-2ccf-11e6-82c9-27bdd439e7a8.png)

**Comment by joshuago78** [comment]
Alyx has been working on implementing the Export button through the API ( see PR #501 ). Once that branch is merged the Export DC should work, but the RIS still needs to be implemented (only on the front end, the API already supports it in her PR).
