### ISSUE TITLE
Disable Angular Debug Mode to Improve Performance

### ISSUE THREAD

**Issue by adamcee** [gri-is/portal#515]
http://blog.thoughtram.io/angularjs/2014/12/22/exploring-angular-1.3-disabling-debug-info.html

Also mentioned in Angular Docs.

- [x] Disable Angular debug mode if app is in production environment

@joshuago78 Not critical but is supposed to noticeably increase performance.

**Comment by joshuago78** [comment]
Yes, let's try to speed it up. It is noticeably slower

**Comment by joshuago78** [comment]
We should make this a variable that we configure with Gulp

**Comment by adamcee** [comment]
Jenny and I did a test of this on grp.dev and for loading a search results page with several facets load time dropped from 1800ms to 600ms. Very easy to implement will do Thurs. 

I agree about the variable setting. I was thinking of adding an `env` property to the .json config files. So, for `config/prod/app.env.json` `env: 'prod'` -- angular can then check `config.env` and set debug mode accordingly.
