### ISSUE TITLE
save record button does not change color in mobile Safari

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#517]
Not sure if this is just a CSS bug with image transition or if this is a functional problem. Will investigate further. In the meantime, see screenshots from an iPhone 5S

![img_2598](https://cloud.githubusercontent.com/assets/349633/15903222/6dbc7018-2d60-11e6-8187-d0628bd6e5cd.jpg)

![img_2599](https://cloud.githubusercontent.com/assets/349633/15903224/6f8d365c-2d60-11e6-9155-bcd27da5ab7f.jpg)

**Comment by joshuago78** [comment]
I am still not sure if this is an Angular problem or a CSS problem. But the bookmark will change colors onl only after it has been tapped twice on the iPhone 5s.

Language from non-dev team user:
"if I click once in a flag for an item it has text below that says save record...if I click a second time, it highlights the tag orange and the text below changes to remove record. The third click removes it. "

**Comment by jfranco-gri** [comment]
I looked at portalbeta on my iPhone and it seems like the first click is triggering the hover effect of the saved record button. Then the second click actually clicks the button and the record is saved. I found this article explaining it and it seems this is a "feature" of iPhones (Android doesn't do this):

https://www.powderkegwebdesign.com/ever-wonder-links-mobile-browsers-require-click-twice/

In that it says the solution is to disable hover effects for mobile.

**Comment by joshuago78** [comment]
OK, I leave it to @kristenGRI to decide if we should call this a feature or a bug.

**Comment by kristenGRI** [comment]
@joshuago78 @jfranco-gri this is a good question and something I was noticing as well. I would like to do a little research and see if any popular sites disable this feature or if it has become common practice and something most users would understand. But my gut instinct is that we disable the hover feature so items are saved on a single click for touch devices. Seems kind of annoying to have to click it twice.
