### ISSUE TITLE
Book and Raw API endpoints should handle nonexistent records

### ISSUE THREAD

**Issue by adamcee** [gri-is/portal#518]
- [ ] Said endpoints should check the HTTP status code of Elasticsearch's response, and that the response contains expected data (that `hits` property exists or something). This is in `api/view.py`
  - [ ] If everything is OK (200) response code executes as normal.
  - [ ] If Elasticsearch response has an error status code because the record was not found, endpoints should handle error.
    - [ ] "Raw" endpoint should not call dc_export function on the bad response
    - [ ] Both endpoints should construct a Response object which contains the error HTTP status code, and `error` property which looks something like: 
  
  `````
error: { 
    "type": "NONEXISTENT_RECORD", 
     "data": "<grp_id_of_missing_record_here" 
}
``````

**Comment by adamcee** [comment]
@joshuago78 The client-side error handling PR fails gracefully this case. But our API code should handle its errors for safety in production. Also this will enable the cilent to inform the user that the record they requested does not exist.

**Comment by joshuago78** [comment]
if the item does not exist in ES, then Django should return a 404. If there is a problem it should return a 500
