### ISSUE TITLE
faceting bug

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#535]
1. go to http://portalbeta.getty.edu
2. search for "painting"
3. Observe the "M. Knoedler & Co." facet in the Creator/Contributor facet category says it will narrow your results 311 hits
4. click on that facet
5. observe that you get 0 results instead

**Comment by joshuago78** [comment]
I suspect this has something to do with the special symbol escaping that was introduced recently

**Comment by adamcee** [comment]
After launch we should make sure we have a unit or E2E test to cover this case (if we don't already) ...

**Comment by jfranco-gri** [comment]
It looks like this is happening because the api is parsing the url string and splitting up the url on '&' characters. So if you have in your url 'creator=Harper & Brothers' it creates a parameter 'creator': 'Harper' and then throws away the '& Brothers' part

**Comment by jfranco-gri** [comment]
Actually, for a url such as this: `/api/books/from=0&size=25&sort=relevance&creator=Harper%20%26%20Brothers` (%26 is the url-encoded '&')

it's splitting up the parameters like so:
`{'creator': ['Harper '], ' Brothers': [''], 'from': ['0'], 'sort': ['relevance'], 'size': ['25']}`

then, because we don't look for any parameters named ' Brothers' it just ignores that. But, since there are no creator facets with the value 'Harper ' Elasticsearch doesn't return any results.

**Comment by jfranco-gri** [comment]
I got this case working. Before I split up the params, I search for occurrences of the pattern ' & ' and replace it with ' %26 '. This works for facets where there's a space follow by & followed by another space, such as 'Harper & Brothers' or 'M. Knoedler & Co.'  But if someone runs a search with an ampersand without a space, such as 'art&science' or 'Harper&Co' the same problem will result.  Is this likely to be a concern?

The only thing I can think of to really fix it is to replace &'s with some other character combination on the client side, then decode it back to & on the Django side after splitting up the parameters.  This is similar to what is already happening when the browser replaces '&' with '%26', but we need some way to differentiate between ampersands that are part of a parameter value and ampersands that are the delimiter between parameter key-value pairs.

**Comment by joshuago78** [comment]
I think we can shelve the use case of somebody searching for "x&y" with no spaces
