### ISSUE TITLE
check if pop blockers affect usability

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#578]

**Comment by kristenGRI** [comment]
I ran through the site in Chroma and clicked on many titles filtering by "From" as well as sorting the full set of all titles by Newly Added, Relevance, and Title. 
-I didn't run into any issues accessing the detail page.
-I didn't run into any issues with the original title location opening in a new tab

The closest I got to reproducing what sounds like the issue, was the fault of the third party. It seems like the PDF for the title below is very large and has problems loading. But I waited a few minutes and tried again and got it to load fine:
http://portal.getty.edu/books/artic_.b1529328

I used chrome's settings to block pop-ups. Might need to know what version Chrome she is using and if she is using third-party pop-up blockers.
