### ISSUE TITLE
refactor unit tests

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#598]
Dozens of unittests fail when the `elasticsearch` package is uninstalled from the Bower components. However, we are no longer using `elasticsearch` package in the client. These unit tests will need to be rewritten with mock data or as integration tests that use the API.

**Comment by jfranco-gri** [comment]
These files use elasticsearch as part of the setup for the tests:
```
contributors/contributors.unit.spec.js
core/search-sort.unit.spec.js
search/search-controller.unit.spec.js
```

It looks like this:

```
beforeEach(function(){
		module('ui.router');
		module('ui.bootstrap');
		module('elasticsearch');
		module('app.core');
		module('app');
		module('app.search');
		module('app.contributors');
	});
```

We probably just need to remove `module('elasticsearch')` from those files
