### ISSUE TITLE
inconsistent creator results

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#619]
Text from a user's feedback:
> You’ll notice that the title, Melische Thongefässe comes up in a keyword search:
>  
> http://portal.getty.edu/search?q=melische%20thongef%C3%A4sse&from=0&size=25&sort=relevance
>  
> but not in a search for the author:
>  
> http://portal.getty.edu/search?from=0&size=25&sort=relevance&adv_creator=Conze,%20Alexander,

**Comment by jfranco-gri** [comment]
This is because Alexander Conze is set to the contributor field, not the creator field. If you search for a creator using Advanced Search, right now runs that search only on the creator field. If you search for Conze, Alexander using the regular keyword search, Melische Thongefässe shows up.

**Comment by joshuago78** [comment]
OK, let's make advanced search query both creator and contributor.
