### ISSUE TITLE
move View Digital Item button

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#627]
On the item detail pages, users are not immediately seeing the "View Digital Item" button.
- [x] @kristenGRI will determine new position
- [x] @susanley  will make desired changes

**Comment by kristenGRI** [comment]
Based on some of our feedback, I think placing the button in a similar place as it is on the detail page is best. This seems to be the most consistent. Please let me know if you disagree. (comp attached)
![rp_itemdetail_v2 1](https://cloud.githubusercontent.com/assets/15019503/19058107/971f4608-8989-11e6-9708-431facddb268.jpg)

**Comment by joshuago78** [comment]
Looks good to me. :+1:

**Comment by susanley** [comment]
@kristenGRI Noted. 😃
