### ISSUE TITLE
users uncertain which date is being used

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#631]
- Q1: Should we enable search for different types of dates?
  - A: **No** (will create too much complexity, and source data is not rich enough too support this)
- Q2: OK then what do we do instead?
  - a1: specify that we are using publication dates (is this always true?)
  - a2: do nothing
  - a3: something else?

**Comment by kristenGRI** [comment]
@joshuago78 I think we should make it transparent what date we are searching for by possibly adding a that to the date slider label  (if we aren't always searching the same date, we should consider stating in which circumstances it might search another date. This advanced explanation could either be a link to the FAQ's or in a tooltip.) 

@alyxrossetti can you shed any light on how the system is currently filtering by date?
