### ISSUE TITLE
Convert all dependency injection to use array notation

### ISSUE THREAD

**Issue by adamcee** [gri-is/portal#64]
Go through the application. Change any dependency injection for services, controllers, etc, to use array notation where it is not used. Array notation is minification-safe; the other method of dependency injection is not. We should make this our coding standard moving forward.

Check files below and update function declaration to follow style guide -- functions should be declared outside of array bracket injection.  https://github.com/johnpapa/angular-styleguide#style-y091
- widgets.config.js
- HomePageCtrl in app.module.js
- app.config.routing.js

This can wait until any bigger tasks are done.

*Reference:*
http://stackoverflow.com/questions/30088534/reason-for-using-array-notation-when-defining-angularjs-controller

**Comment by susanley** [comment]
@joshuago78, went through all js files using dependency injection, all are currently written using array notation. Double checked references files with @adamcee. No changes need to be made. If there is a problem when we minify, we can revisit.
