### ISSUE TITLE
make ingest storage location configurable

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#667]
In production, we don't really want data living with the code.

Add a setting in `settings.py` for the location of the source files (both original and derivatives).

**Comment by alyxrossetti** [comment]
`PRODUCTION_DATA = os.path.join(BASE_DIR, 'ingest/production_data')`

is already in `settings.py`....is this not what you mean?

**Comment by joshuago78** [comment]
Ah, OK. I forgot that was there.
