### ISSUE TITLE
add dc:source elements

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#702]
- [x] Add a `dc:source` element with value of Getty Research Portal to every record
- [x] Add a `dc:source` element with value of the contributing institution to every record

**Comment by alyxrossetti** [comment]
@joshuago78 Currently the json export uses lists for elements with multiple values, and the xml has actual repeating elements.  Do we want to change the json formatting or should I keep things the same and use a list for `dc:source`?

`dc:subject: [
"Monuments historiques -- Inventaires -- France -- 19e siècle",
"Patrimoine culturel -- Inventaires -- France -- 19e siècle",
"Province -- France -- 19e siècle"
]`

`<dc:subject>Monuments historiques -- Inventaires -- France -- 19e siècle</dc:subject>
<dc:subject>Patrimoine culturel -- Inventaires -- France -- 19e siècle</dc:subject>
<dc:subject>Province -- France -- 19e siècle</dc:subject>`

**Comment by joshuago78** [comment]
Use a list. We cannot have an object (dictionary) with two identical keys.

**Comment by alyxrossetti** [comment]
obviously...
