### ISSUE TITLE
Export Book Metadata

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#72]
From the Book Details page, the user should be able to export the book details/metadata. 

From page 10 of the design doc:
*“Export” button opens a drop-down with options for different export types. Clicking one will download the record in the selected format.*

Formats include:
- [x] DC-JSON
- [ ] DC-XML
- [ ] DC-YAML
- [x] RIS

**Comment by jfranco-gri** [comment]
I can implement the server-side code, but we need to figure out the transformation going from json to RIS. I don't know what our fields in JSON/DC correspond to in RIS.

**Comment by joshuago78** [comment]
@alyxrossetti can you please assist @jfranco-gri with mapping DC to RIS. The mapping does not need to be exhaustive, just enough for citations.

**Comment by alyxrossetti** [comment]
Here is a list of all RIS fields used in the current Portal:

`r_TY
r_TI
r_T2
r_T3
r_AB
r_AU
r_ET
r_KW
r_CY
r_CN
r_N1
r_N2
r_PB
r_PY
r_SP
r_LA
r_KW
r_SN
r_T2
r_UR`

I will look into it and see if there are any we can drop and then also get you a mapping @jfranco-gri

**Comment by alyxrossetti** [comment]
![image](https://cloud.githubusercontent.com/assets/9535150/15477847/dfcef316-20cb-11e6-8f96-267bd704d95a.png)

@joshuago78 This is where I'm at thus far - let me know if you have input.  The only thing left to do is try to map the "types"

**Comment by alyxrossetti** [comment]
@joshuago78  Here is the mapping for the "types" - it really is problematic but I did my best.  The other option is to just map everything to GEN (Generic)

![image](https://cloud.githubusercontent.com/assets/9535150/15482473/c01ccd40-20e4-11e6-94b3-68372024ddb8.png)

**Comment by joshuago78** [comment]
I think this will work fine.
